#!/usr/bin/env python
# (Be in -*- python -*- mode.)
#
# ====================================================================
# Copyright (c) 2000-2008 CollabNet.  All rights reserved.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution.
#
# This software consists of voluntary contributions made by many
# individuals.  For exact contribution history, see the revision
# history and logs.
# ====================================================================

import sys
import os

from cvs2svn_lib.common import FatalException
from cvs2svn_lib.main import git_main


try:
  git_main(os.path.basename(sys.argv[0]), sys.argv[1:])
except FatalException as e:
  sys.stderr.write(str(e) + '\n')
  sys.exit(1)


